### ISSUE TITLE
Pypi link is broken

### ISSUE THREAD

**Issue by marcusps** [rigetticomputing/reference-qvm#1]
[Pypi](https://pypi.python.org/pypi/referenceqvm) lists the homepage as https://github.com/rigetticomputing/referenceqvm when it should be https://github.com/rigetticomputing/reference-qvm

Installation through pip works regardless, though.

**Comment by willzeng** [comment]
Thanks @marcusps !  I fixed this in the `setup.py` and the next release will fix this on pypi
