### ISSUE TITLE
Installation by pip fails

### ISSUE THREAD

**Issue by TheThirdOne** [rigetticomputing/reference-qvm#4]
The README suggests installing using pip by:
```
pip install reference-qvm
```

but this fails with the error message:

```
Collecting reference-qvm
  Could not find a version that satisfies the requirement reference-qvm (from versions: )
No matching distribution found for reference-qvm
```

Installing `referenceqvm` works fine though. 

The name in setup.py should probably be updated.

#1 was a similar issue.

**Comment by ncrubin** [comment]
I believe this has been addressed.
